// This file is auto-generated by the tool factory. Do not edit it manually.
import authTools from "./auth";
import type { ToolDef } from "../tool-factory";

export default [
  ...authTools
] as ToolDef[];
